export const INCREMENT_PRODUCT = 'ICREMENT_PRODUCT';
export type INCREMENT_PRODUCT = typeof INCREMENT_PRODUCT;

export const DECREMENT_PRODUCT = 'DECREMENT_PRODUCT';
export type DECREMENT_PRODUCT = typeof DECREMENT_PRODUCT;

export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export type REMOVE_PRODUCT = typeof REMOVE_PRODUCT;
